# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

steps:
- script: echo Deze web-app is gemaakt door een Azure Pipeline & Damian Luijkx!
  displayName: 'Run a one-line script'