# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

steps:
- script: echo Deze web-app is gemaakt door een Azure Pipeline
  displayName: 'Run a one-line script'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'ServiceConn-SeniorConnect'
    appType: 'webApp'
    WebAppName: 'SC-Wapp-001'
    packageForLinux: 'index.html'