trigger:
  branches:
    include:
      - main

pool:
  name: Azure Pipelines

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ServiceConn-SeniorConnect'
    appName: 'Wapp-SeniorConnect-001'
    package: $(Build.ArtifactStagingDirectory)
